### ISSUE TITLE
Net::ReadTimeout on reconfigure boot type

### ISSUE THREAD

**Issue by JerrodCarpenter** [vmware/vsphere-automation-sdk-ruby#67] opened 2019-12-19 00:28 UTC
## Describe the bug

When attempting to deploy an OVF, we receive a `Net::ReadTimeout`

Stack trace:
```ruby
Net::ReadTimeout
/usr/local/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
/usr/local/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/usr/local/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
/usr/local/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
/usr/local/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
/usr/local/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
/usr/local/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
/usr/local/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
/usr/local/lib/ruby/2.6.0/net/http.rb:1479:in `request'
/opt/app/vendor/bundle/ruby/2.6.0/gems/ruby-ntlm-0.0.4/lib/ntlm/http.rb:22:in `request'
/opt/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/net.rb:36:in `block in request_with_newrelic_trace'
/opt/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent.rb:506:in `disable_all_tracing'
/opt/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/net.rb:35:in `request_with_newrelic_trace'
/usr/local/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
/usr/local/lib/ruby/2.6.0/net/http.rb:920:in `start'
/usr/local/lib/ruby/2.6.0/net/http.rb:1470:in `request'
/opt/app/vendor/bundle/ruby/2.6.0/gems/ruby-ntlm-0.0.4/lib/ntlm/http.rb:22:in `request'
/opt/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/net.rb:36:in `block in request_with_newrelic_trace'
/opt/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent.rb:506:in `disable_all_tracing'
/opt/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/net.rb:35:in `request_with_newrelic_trace'
/opt/app/vendor/bundle/ruby/2.6.0/gems/vsphere-automation-runtime-0.4.6/lib/vsphere-automation-runtime/api_client.rb:71:in `call_api'
/opt/app/vendor/bundle/ruby/2.6.0/gems/vsphere-automation-vcenter-0.4.6/lib/vsphere-automation-vcenter/api/vm_hardware_boot_api.rb:124:in `update_with_http_info'
/opt/app/vendor/bundle/ruby/2.6.0/gems/vsphere-automation-vcenter-0.4.6/lib/vsphere-automation-vcenter/api/vm_hardware_boot_api.rb:83:in `update'
```

## How to reproduce

```ruby
configuration = VSphereAutomation::Configuration.new.tap do |c|
  c.host = @name
  c.username = @user
  c.password = @pass
  c.scheme = 'https'
  c.timeout = 7_200
  c.verify_ssl = false
  c.verify_ssl_host = false
end
@rest = VSphereAutomation::ApiClient.new(configuration)
VSphereAutomation::CIS::SessionApi.new(@rest).create('')

# Once VM is created, update the boot type where ID is vm id.
VSphereAutomation::VCenter::VmHardwareBootApi.new(@rest).update(id, { spec: { enter_setup_mode: false, efi_legacy_boot: false, type: 'EFI' } })
```

## Expected behavior

I'd expect the boot type to be configured without timeout

## Versions

**Dev Environment:**

* Ruby: `2.6.3`
* vSphere Automation SDK: `0.4.6`
* OS: macOS `10.14.6`

## Additional notes

Seems related to:
* https://github.com/vmware/vsphere-automation-sdk-ruby/issues/59
* https://github.com/vmware/vsphere-automation-sdk-ruby/issues/60

**Comment by jrgarcia** [comment] 2019-12-19 15:55
Weird. I'm not sure what's going on, but I'll take a look today.

**Comment by jrgarcia** [comment] 2019-12-19 16:52
@JerrodCarpenter I just want to clarify a few things to make sure I'm looking at the issue correctly. Are you having issues with a timeout when making an API call? Is the request going through, but taking longer than the allotted timeout? Is the request making it to the vCenter instance and if so, what is happening on the vCenter side? What exactly do you mean by `I'd expect the boot type to be configured without timeout`?

**Comment by JerrodCarpenter** [comment] 2019-12-19 17:30
> I just want to clarify a few things to make sure I'm looking at the issue correctly. Are you having issues with a timeout when making an API call?

The request hangs, and the standard library ruby request code hits the timeout time. If you can help me understand how to send this same API call with just Postman, I'm happy to try that if it'd better narrow down a root cause.

> Is the request going through, but taking longer than the allotted timeout?

The request is going through, and the task completes in 7 ms.

> Is the request making it to the vCenter instance and if so, what is happening on the vCenter side?

The request makes it there, and the vcenter makes the change.

> What exactly do you mean by I'd expect the boot type to be configured without timeout?

Sorry, I just mean I don't expect it to timeout as the operation has worked in the past without issue and the timeout is set to two hours.

**Comment by jrgarcia** [comment] 2019-12-19 18:36
@JerrodCarpenter I'm going to go ahead and close this based on our discussion offline.

For anyone reading this later, it appears the issue is on the server side rather than the client side.

**Closed by jrgarcia** 2019-12-19 18:36 UTC
Labels: bug

**Comment by JerrodCarpenter** [comment] 2019-12-19 18:46
We used curl to confirm that the rest api is responsible for the hang instead of the sdk.
